-- Daily AI risk briefings, generated by a morning batch job (utils/dailyBrief.js).
-- One row per scope per run: the ops portfolio, plus one per client account owner.
-- The portal reads the latest row for its scope; history is kept for trend/audit.
CREATE TABLE IF NOT EXISTS daily_briefings (
  id            BIGSERIAL PRIMARY KEY,
  scope         TEXT NOT NULL,                         -- 'ops_portfolio' | 'client'
  owner_id      INTEGER REFERENCES users(id),          -- NULL for ops; client account owner for 'client'
  generated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ai            BOOLEAN NOT NULL DEFAULT FALSE,         -- true = LLM-written, false = template fallback
  provider      TEXT,
  model         TEXT,
  briefing      TEXT NOT NULL,
  portfolio     JSONB,                                 -- triage counts snapshot
  structured    JSONB                                  -- the data the briefing was built from
);

CREATE INDEX IF NOT EXISTS idx_daily_briefings_scope_time
  ON daily_briefings (scope, owner_id, generated_at DESC);
